name: metaclassifier-datahub-actions

source:
  type: datahub-cloud
  config:
    topics:
      - PlatformEvent_v1
      - MetadataChangeLog_Versioned_v1
      - MetadataChangeLog_Timeseries_v1

datahub:
  server: ${DATAHUB_GMS_URL:-http://datahub-gms:8080}
  token: ${DATAHUB_GMS_TOKEN:-}

action:
  type: services.event_ingestion_service.app.datahub_action:DataHubMetaClassifierAction
  config:
    event_ingestion_url: http://event-ingestion:8001/ingest
